### ISSUE TITLE
Any debug options?

### ISSUE THREAD

**Issue by strzibny** [basecamp/kamal-proxy#32]
Once the proxy receive a particular configuration like:

```bash
 docker exec kamal-proxy kamal-proxy deploy app-web --target ... --host ...
```
I would like to know the proxy's current full configuration.

How can we recheck what's actually set, especially running more services?

**Comment by djmb** [comment]
`docker exec kamal-proxy kamal-proxy list` will show you what's currently enabled, though it doesn't show you all the settings and it's not been exposed by the kamal gem yet.

**Comment by strzibny** [comment]
Thank you. I think exposing it would be useful, but closing the issue.
