### ISSUE TITLE
Avoid buffering X-Accel-Buffering responses

### ISSUE THREAD

**Issue by djmb** [basecamp/kamal-proxy#34]
To allow Server Sent Events to always work, we should always disable buffering for responses with the `X-Accel-Buffering` header set to `no`.

See here - https://github.com/basecamp/kamal/issues/1017#issuecomment-2385704040

**Comment by kevinmcconnell** [comment]
I think instead we should skip the buffer for responses that have a `Content-Type: text/event-stream`. That way SSE will work without having to do anything special.

`X-Accel-Buffering` is (I think?) an nginx-specific header.

**Comment by mythz** [comment]
We also need to disable buffering for our [Blazor Streaming Rendering](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/rendering?view=aspnetcore-9.0#streaming-rendering) pages which doesn't work behind kamal proxy.

Can you also support a custom header to disable buffering like `X-Accel-Buffering:no` as suggested? Happy with any custom HTTP Header, we just need to be able to disable it on specific pages/http requests.
