### ISSUE TITLE
Docs missing on how to update

### ISSUE THREAD

**Issue by krtschmr** [basecamp/kamal-proxy#38]
installed a new Kamal deploy on a server last week, now want to deploy another project with latest rails:master and receive 
`  ERROR (RuntimeError): Exception while executing on host 37.27.1.178: kamal-proxy version v0.6.0 is too old, please reboot to update to at least v0.7.0`

running 0.6
`c3526c2bfda7   basecamp/kamal-proxy:v0.6.0                              "kamal-proxy run"        3 days ago   Up 2 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   kamal-proxy
`

while i certainly want to upgrade, nowhere can i find help on what to do.

**Comment by kevinmcconnell** [comment]
@krtschmr you can upgrade to the latest proxy version with `kamal proxy reboot`. That's the "reboot" that the error message is referring to, and the docs for that command are [here](https://kamal-deploy.org/docs/commands/proxy/).

Agree we could make this clearer though! Thanks for pointing it out.

I'll make a note in the Kamal project to clarify that error message a bit more. The change will belong in that project.
