### ISSUE TITLE
Maintenence mode

### ISSUE THREAD

**Issue by djmb** [basecamp/kamal-proxy#4]
There's a long standing request for supporting maintenance mode via Kamal. Could we do this with the proxy?

1. Build a custom image that serves maintenance pages
2. Add a command to switch to maintenance mode which switches to that image.

We'd need a way to customise the maintenance page and need to make sure to return all the right response codes.

See https://github.com/basecamp/kamal/issues/162

**Comment by dhh** [comment]
We need to expose this with something like `kamal proxy stop/pause`, yeah?

**Comment by kevinmcconnell** [comment]
That's right, yes. The proxy side of it is done, so we'll just need to expose these commands through Kamal's CLI. Not sure if we'll have that in 2.0, or a 2.1 follow-up -- @djmb what do you think?

**Comment by djmb** [comment]
We'll leave this for 2.1 I think.
