### ISSUE TITLE
Question: Is it possible to change the gateway timeout duration of kamal-proxy?

### ISSUE THREAD

**Issue by augustine667** [basecamp/kamal-proxy#53]
Is it possible to modify the Kamal-proxy gateway timeout duration?  How can I accomplish that with Kamal Deploy as well, if it's feasible?
Many thanks!

**Comment by morgoth** [comment]
what do you exactly mean by "gateway timeout"
If it's about server response timeout then yes -> https://github.com/basecamp/kamal-proxy/blob/e66b63a6f1468c7d32d77db235ad89ece896f61c/internal/cmd/deploy.go#L43
in kamal it's controlled by https://kamal-deploy.org/docs/configuration/proxy/#response-timeout

**Comment by bhtabor** [comment]
If you are using thruster with kamal proxy, you would need to increase the http read and/or write timeouts too. https://github.com/basecamp/thruster?tab=readme-ov-file#custom-configuration
