### ISSUE TITLE
Server-Sent Events is still being buffered if charset is set in Content-Type

### ISSUE THREAD

**Issue by hovoere** [basecamp/kamal-proxy#54]
If charset is set on Content-Type server-sent events will still be buffered.
eg.
content-type: text/event-stream; charset=utf-8

Looks like #36 is checking for exact match on "text/event-stream"

**Comment by karls** [comment]
The `charset` parameter is [optional](https://html.spec.whatwg.org/multipage/iana.html#text/event-stream) as the content must be encoded in UTF-8 anyway. But yes, technically it can be supplied by the server and should be supported by the proxy.

**Comment by hovoere** [comment]
Yes. I was wondering why it didnt work for me, as i only set text/event-stream and dont specify the charset, but apparently Express adds the charset automatically.

**Comment by kevinmcconnell** [comment]
Thanks for reporting, @hovoere & @karls! This is fixed on main now, and will be in the next release.

**Comment by imWildCat** [comment]
@kevinmcconnell sorry to bother: when will the next version with this fix be released?

is there any option for kamal 2 users to use the latest code on the main branch?

**Comment by kevinmcconnell** [comment]
@imWildCat I think there will be a Kamal release tomorrow, which will contain this fix. Sorry about the delay!

In terms of using the latest (unreleased) proxy versions in Kamal, we don't have a way to do that right now, but we've discussed adding one. Probably something like a spot in the config to add a different image path/tag. I'll see if we can get something in place for that soon too.

**Comment by imWildCat** [comment]
@kevinmcconnell no worries at all! I just discovered this issue last night and will use CF Tunnels in my app container to expose the streaming api temporarily.

thanks for your work! ❤️

**Comment by kevinmcconnell** [comment]
@imWildCat the new Kamal release is available now, which has this fix: https://github.com/basecamp/kamal/releases/tag/v2.3.0

**Comment by imWildCat** [comment]
@kevinmcconnell sorry for the late reply!
it works perfectly now!
