### ISSUE TITLE
how to cleanup state after renaming a service

### ISSUE THREAD

**Issue by koenhandekyn** [basecamp/kamal-proxy#61]
context: one server with multiple apps/services running

i had an app i first called 'prod', i deployed it, it works.

i renamed the app to 'production', i tried to deploy it, it fails as kamal proxy says their is a hostname conflict.  reinstalling, stopping, removing the app all didn't fix the kamal proxy corruption. 

i found that the state is stored in a state file and indeed the 'old' entry still is there.

not sure if this is a kamal or a kamal proxy issue, but something is needed to remove old entries from this state file?

```json
[
  {
    "name": "allcrux-corpware-web-prod",
    "hosts": [
      "app.allcrux.com"
    ],
    "active_target": "a9c99e1157d9:80",
    "rollout_target": "",
    "options": {
      "tls_enabled": true,
      "tls_certificate_path": "",
      "tls_private_key_path": "",
      "acme_directory": "",
      "acme_cache_path": "/home/kamal-proxy/.config/kamal-proxy/certs",
      "error_page_path": ""
    },
    "target_options": {
      "health_check_config": {
        "path": "/up",
        "interval": 1000000000,
        "timeout": 5000000000
      },
      "response_timeout": 30000000000,
      "buffer_requests": true,
      "buffer_responses": true,
      "max_memory_buffer_size": 1048576,
      "max_request_body_size": 0,
      "max_response_body_size": 0,
      "log_request_headers": [
        "Cache-Control",
        "Last-Modified",
        "User-Agent"
      ],
      "log_response_headers": null,
      "forward_headers": false
    },
    "pause_controller": {
      "state": 0,
      "stop_message": "",
      "fail_after": 0
    },
    "rollout_controller": null
  } ...
]
```

**Comment by kevinmcconnell** [comment]
@koenhandekyn you can remove the old deployment in Kamal before deploying the renamed version. I think you're running into the same situation as https://github.com/basecamp/kamal/issues/1147. By renaming it, Kamal treats this as two different deployments, which leads to the conflict.

If you do need to clean up state manual, you can do that with `kamal-proxy remove` (there's an example of that at the end of the linked ticket).
