### ISSUE TITLE
How to set CORS headers?

### ISSUE THREAD

**Issue by dgtllion** [basecamp/kamal-proxy#62]
Is it possible to add some CORS headers to proxy?
Something like this? 
```
Access-Control-Allow-Origin app.domain.com
Access-Control-Allow-Methods: GET,HEAD,POST,PUT,OPTIONS,DELETE,PATCH
```

This i what i have for my apache config.
```
    SetEnvIf Origin "^https://(\w+\.)?domain\.com$" AccessControlAllowOrigin=$0
    Header always set Access-Control-Allow-Origin %{AccessControlAllowOrigin}e env=AccessControlAllowOrigin
    Header always set Access-Control-Allow-Credentials true
    Header always set Access-Control-Allow-Methods: GET,HEAD,POST,PUT,OPTIONS,DELETE,PATCH
    Header always set Access-Control-Allow-Headers "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version"

```

Its needed to communicate with api. 
In my situation i use multiple domains
https://account.domain.com
https://app.domain.com
https://api.domain.com

When i try to call api from app it gives me an error: 
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

**Comment by frenkel** [comment]
Isn't it possible to send these from your app? If it's Rails I'm pretty sure you can do it from there.

**Comment by dgtllion** [comment]
In the app i can add it, but how is it possible to add it into a kamal-proxy configuration?

**Comment by frenkel** [comment]
Why do you want to make the kamal-proxy more complex when you can solve it in your app already? I think it's out of scope.

**Comment by kevinmcconnell** [comment]
Yes, as @frenkel mentioned, configuring additional headers like this is not something Kamal Proxy provides. You can set them in your app (or at another proxy layer if you prefer to do that).
