### ISSUE TITLE
Request: Add X-Request-Start header

### ISSUE THREAD

**Issue by AxelTheGerman** [basecamp/kamal-proxy#69]
Love the new kamal-proxy and I know we want to keep it simple and not add too many features.

However, I was hoping - similar to `X-Request-Id` - we could add `X-Request-Start` header for all incoming requests. This would allow any downstream system to assess the queuing time, which is probably the most important metric the app itself cannot determine.

All major monitoring systems seem to support this header and pick it up automatically when it's set - skylight, datadog, new relic etc.

```
proxy_set_header X-Request-Start "t=${msec}";
```

For more context: https://pawelurbanek.com/rails-performance-fixes#eliminate-request-queue-time

I know that we could require users to run a separate proxy, but I'd argue that the simplicity of this should hopefully qualify for similar treatment as the request ID.

**Comment by kevinmcconnell** [comment]
Completely agree, @AxelTheGerman! Thanks for your suggestion and contribution.

Added in #70.
