### ISSUE TITLE
Rollout

### ISSUE THREAD

**Issue by kevinmcconnell** [basecamp/kamal-proxy#8]
We'll add a rollout feature to enable people to do gradual rollouts of app changes. It works like this:

- In addition to deploying your app's target, you can also specify a rollout target. Traffic deemed to belong to the rollout group will be proxied to the rollout target rather than the regular one.
- A new `rollout` command controls how traffic is split between versions.
- The rollout routing is cookie-based. You specify the name of a cookie to use. The proxy reads the value of that cookie to determine where the traffic goes. This is how you integrate the rollout behaviour into your app.
- You can specify the split either as a list of values ("roll out to these users"), a percentage of values ("roll out to 20% of the users"), or a combination of both ("roll out to 20%, and also to these specific users").
- For percentage splits, we hash the cookie value and split the hash space at the percentage point. For lists, we use the literal value.

Currently we can specify a number of configuration options whenever we deploy a target (timeouts, TLS options, etc). For simplicity I think we'll want to enforce that the same settings apply to both targets during a rollout period. That means you can't use this same feature to rollout out changes to those deploy settings, but I think it's worth it to avoid the complexity of juggling both and to keep the feature simple; this is really about rolling out app versions, not proxy configuration.

**Comment by dhh** [comment]
Has this been exposed directly in kamal too?

**Comment by kevinmcconnell** [comment]
Not yet. It's the same situation as #4 -- the proxy has the feature now, but wiring up the Kamal side is still on the todo list.
